services:
    gs2-docs:
        image: nginx:alpine
        container_name: gs2-docs
        volumes:
            - ./html:/usr/share/nginx/html:ro
        restart: unless-stopped
        networks:
            - nginx_network

networks:
    nginx_network:
        external: true
